name: Coverage

on:
  - push
  - pull_request

jobs:
  coverage:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          # Stay with 1.51.0 until either
          # https://github.com/xd009642/tarpaulin/issues/756
          # or https://github.com/Geal/nom/issues/1311
          # are resolved.
          toolchain: 1.51.0
          override: true
      - name: Install Tarpaulin
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-tarpaulin
      - name: Collect coverage
        uses: actions-rs/cargo@v1
        with:
          command: tarpaulin
          args: --verbose --coveralls ${{ secrets.COVERALLS_TOKEN }}
